openapi: 3.0.0
info:
  title: Flask App API
  description: API for managing user records in a CSV file.
  version: 1.0.0

servers:
  - url: http://localhost:5000

paths:
  /users:
    get:
      summary: Retrieve all users
      responses:
        '200':
          description: A list of users or a message if no users exist.
        '500':
          description: Server error
  /search:
    get:
      summary: Search for a user by name
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User(s) matching the query
        '400':
          description: Bad request, missing username parameter
        '404':
          description: No user found
        '500':
          description: Server error
  /add_user:
    post:
      summary: Add a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                email:
                  type: string
              required:
                - name
                - email
      responses:
        '201':
          description: User added successfully
        '400':
          description: Bad request, missing fields
        '500':
          description: Server error
  /remove_user:
    delete:
      summary: Remove a user by email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: User removed successfully
        '400':
          description: Bad request, missing email field
        '404':
          description: User not found
        '500':
          description: Server error
