name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3  # Adjust if you use a different Python version

      - name: Install dependencies
        run: |
          cd release1/cp1/core  # Navigate to the folder containing manage.py
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Production
        run: |
          echo "Deploying to production on ${{ matrix.os }}..."
          echo "Deployment successful!"
