name: Run Django Tests

on:
  push:
    branches:
      - main
      - registration-login-feature
  pull_request:
    branches:
      - main
      - registration-login-feature

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3  # Adjust if you use a different Python version

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd release1/cp1/core  # Navigate to the folder containing manage.py
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and Run All Python Files
        run: |
          cd release1/cp1/core  # Navigate to the folder containing manage.py
          for file in $(find . -name "*.py"); do
            python -m py_compile $file
            python $file
          done

      - name: Run Tests
        run: |
          cd release1/cp1/core  # Navigate to the folder containing manage.py
          find . -name "*test*.py" -exec python {} \;
