<<<<<<< HEAD
name: Django Test Workflow
=======
name: Python Test Workflow
>>>>>>> Hana-ElGabry-patch-1

on:
  push:
    branches:
<<<<<<< HEAD
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django ipython django-extensions
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test
=======
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installs the dependencies listed in your requirements.txt file

      - name: Run tests
        run: |
          pytest  # Runs the tests with pytest
>>>>>>> Hana-ElGabry-patch-1
